name: "Terraform Change Mangment piepline"

on:
  push:
    branches: ["master"]

concurrency:
  # validate the old workflow and unit ID
  group: ${{github.workflow}}-${{github.sha}}
  cancel-in-progress: true

env:
  #To see the full logs
  TF_LOG: "verdose"
  AWS_ACCESS_KEY_ID: ${{secrects.AWS_ACCESS_KEY_ID}}
  AWS_SECRECT_KEY: ${{secrects.AWS_SECRECT_ACCESS_KEY}}
  AWS_REGION: "us_east_1"

jobs:
  # one job runn on one VM machine
  terraform:
    name: "Terraform Plan & Apply"
    runs_on: ubuntu-latest
    # for the put the code inside the job
  steps:
    - name: Checkout repository
      uses: actions/checkout@

    #Debugging the secrect key and access key
    - name: #Debugging
      run: |
        echo $AWS_ACESS_KEY_ID

    - name: Configure AWS credential
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws_access_key_id: ${{secrects.AWS_ACCESS_KEY_ID}}
    # set up the terraform binary file
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        # Terraform version must be the same with the local use version
        terraform_version: "1.10.1"

    #initialized the terraform
    - name: Init Terraform
      id: Init
      run: |
        terraform init \
        -backend-config="bucket=${{ secrets.S3_BUCKET_NAME }}" \
        -backend-config="key=terraform.tfstate" \
        -backend-config="region=$AWS_REGION"

    #Delcare the variable in the plan step and output this step for reusing the other steps.
    - name: Plan Terrraform changes
      id: plan
      run: |
        terraform plan \
        -out=tfplan \
        -var "VPC_ID" \
        -var "cluster_name= $CLUSTER_NAME" \
        -var "region=$AWS_REGION"" \
        -var "control_plane_subnet_ids=$CONTROL"

    # Security Enchanment and scanning Tools for the IaC code checkov
    - name: Checkov GitHub Action
      uses: bridgecrewio/checkov-action@v12
      with:
        # This will add both a CLI output to the console and create a results.sarif file
        output_format: cli,sarif
        output_file_path: console,results.sarif

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v2

    - name: Apply Terraform changes
      #apply steps is execute when there is changed on the plan stage
      if: steps.plan.outputs.summary != 'No changes. Everything  is update to date.'
      run: terraform apply --auto-approve

    - name:
