name: CI

on:
  push:
    branches:
      - master
jobs:
  #job ids
  Terraform:
    name: "Terraform workflow"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
