name: CI

on:
  push:
    branches:
      - master
jobs:
  #job ids
  Terraform:
    name: "Terraform workflow"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

        #Set up Terraform, be the same version with local

      - name: Terraform Init
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.10.1"
